
obj-y				+= aipc_profile.o

obj-y				+= memory.o

obj-y				+= rpmsg_clk.o

obj-$(CONFIG_AMBALINK_LINKCTRL)	+= rpmsg_linkctrl.o

obj-$(CONFIG_AMBALINK_SD) 	+= rpmsg_sd.o

obj-$(CONFIG_AMBALINK_PPM)      += ppm.o

obj-$(CONFIG_HIBERNATION) 	+= hibernate.o

