obj-$(CONFIG_MISC_PBT) += pbt.o
obj-$(CONFIG_MISC_PGIMBAL) += pgimbal.o
obj-$(CONFIG_MISC_PSFS) += psfs.o
obj-$(CONFIG_MISC_PSHM) += pshm.o
obj-$(CONFIG_MISC_PTEST_CLOCK) += test_clock.o
obj-$(CONFIG_MISC_PTEST_OOPS) += test_oops.o
