obj-$(CONFIG_PARROT_SMARTBATTERY) += smartbattery.o
smartbattery-objs := \
	smartbattery_auth.o \
	smartbattery_charger.o \
	smartbattery_common.o \
	smartbattery_crc16.o \
	smartbattery_gauge.o \
	smartbattery_i2c.o \
	smartbattery_ioctl.o \
	smartbattery_main.o \
	smartbattery_property.o \
	smartbattery_reboot.o \
	smartbattery_simu.o \
	smartbattery_sys.o \
	smartbattery_tps.o \
	smartbattery_update.o \

